### PR TITLE
* switch out bitmap icons for css inlined vector icons

### PR DESCRIPTION
**Pull request by thomasfranz94**
First of all, thank you very much for creating and maintaining chocolat!

I had some problems importing the chocolat css file in my webpack environment.
It would try follow the relative path from my entrypoint.

I had a look at the icons and decided to try and improve the project whilst possibly fixing my issue.

+ swap out per css variable
+ more crisp
+ lower footprint

I hope this is a fitting improvement, please let me know any thoughts you have on this.

### CODE REVIEW

**Comment by thomasfranz94** [comment]
Preview:
https://user-images.githubusercontent.com/48122323/177197492-6ef45e06-c4f3-468c-a26f-10313f1f0dd5.mp4

**Comment by nicolas-t** [comment]
Thanks !

I like the idea :) , you didn't manage to make it work with non-inline svg ?

**Comment by thomasfranz94** [comment]
Thank you!

Non-inline would also work just fine, inlining them does simply eliminate all path resolving issues that might come up like it did for me.
It's also not uncommon and should be pretty usable, see [bootstrap](https://github.com/twbs/bootstrap/blob/6cf72530ed31bc69ed9fa6168bb7629a48cf8884/scss/_variables.scss#L884)

Commiting something to this project goes beyond solving my own problem for me here, so if you'd like for them to not be inlined then that's no prob!

**Comment by nicolas-t** [comment]
Yes, ideally I would like to have svg files, and maybe have them inlined at build time in the `dist` folder.

**Comment by thomasfranz94** [comment]
Great idea, would you also be open for SCSS replacing plain CSS?
If so I'd like to tackle that on a different feature branch beforehand.

**Comment by nicolas-t** [comment]
Thanks !
I really want to keep this project simple, so I don't think adding a css preprocessor would be a good idea.
But what would be the benefits of using SCSS ?

**Comment by thomasfranz94** [comment]
I thought so, good reason!
The benefits I see are maintenance related.
Mostly meaningful nesting, grouping and DRY-reduction:
[css](https://paste.ofcode.org/QUK8HQaEnCrmgmJsiiPs7Z) / [scss](https://paste.ofcode.org/RGYmUgj66neUR92xM5YK4p)
[css](https://paste.ofcode.org/7z6saeiVSK3Dq9a4zJW8jn) / [scss](https://paste.ofcode.org/36kQ2PHvGp4P77NcAn5PYvV)

**Comment by nicolas-t** [comment]
Thanks for adding the SVGs and the build step :)

Can we use this loader instead (the one you added isn't animated)?
https://github.com/SamHerbert/SVG-Loaders/blob/master/svg-loaders/oval.svg


About CSS I love nested css too but I don't think it's worth it for this project.

**Comment by thomasfranz94** [comment]
My pleasure!
For sure, in the making (The current one is animated with CSS keyframes)
I see, uint me up when there is any potential for it some day :)

**Pull request merged**
